# ---------- GENERAL ----------

# If the food level should not go down during a round.
disable-hunger: true

# If players should be able to push each other (damage is still disabled).
enable-pvp: false

# The game mode that players have during the round (e.g., ADVENTURE, SURVIVAL).
game-mode: ADVENTURE

# Projectiles to enable knockback for.
#
# Snowballs and similar projectiles used to have a knockback effect when hitting players. This effect can be re-added
# by including the projectile in the list below.
enable-knockback:
  - snowball
  - egg
  - fishing_hook



# ---------- TAG ----------

tag:
  # Sleep duration after being tagged (in seconds).
  sleep-time: 20
  # Distance a hunter needs to be within of a player death for it to count as a tag event.
  death-distance: -1



# ---------- SCORING ----------

scoring:
  # Levels required to win the round (1 level equals the number of points defined below).
  levels-to-win: 100
  # Points per XP-level.
  points-per-level: 100
  # Server ticks between each score update tick.
  update-period: 1
  # Points gained per score update tick.
  points-per-tick: 1
  # Points gained for tagging another player.
  points-on-tag: 0
  # Points gained for getting tagged by a hunter (can be negative for losing points).
  points-on-tagged: -0
  # Range (in blocks) to be within of a (non-sleeping) hunter to gain points. -1 to disable the range check.
  hunter-distance: 40



# ---------- INVENTORY ----------

hunter:
  leather-color: 0xFF0000
  items:
    hunter_compass: 1
    hunter_speed_boost: 1
    hunter_bow: 1
    arrow: 1

runner:
  leather-color: 0x0000FF
  items:
    swapper_ball: 1
    egg: 5
    chorus_fruit: 3
    invis_potion: 1
    runner_speed_boost: 3
    balloon_grenade: 1



# ---------- CUSTOM ITEM SETTINGS ----------

custom-item:
  swapper_ball:
    consumable: false
    cooldown: 30.0
    allow-hunter-swap: false

  speed-boosts:
    hunter_speed_boost:
      consumable: false
      cooldown: 10.0
      duration: 5.0
      level: 1
    runner_speed_boost:
      consumable: true
      cooldown: 5.0
      duration: 0.2
      level: 50

  invis_potion:
    duration: 10.0

  balloon_grenade:
    consumable: true
    cooldown: 0.0
    duration: 5.0
    level: 2
