name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: 1.13
authors: [Gimme]
description: ${project.description}
softdepend: [ProtocolLib]

commands:
  tag:
    aliases: t
    description: All tag commands
    usage: "Unknown command. Type \"/tag help\" for help."
    permission: gimmetag.tag

permissions:
  gimmetag.*:
    description: Wildcard permission
    children:
      gimmetag.tag.*: true

  gimmetag.tag.*:
    description: Can use all tag commands

  gimmetag.tag:
    description: Can use tag commands
    default: true
  gimmetag.tag.hunter:
    default: true
  gimmetag.tag.runner:
    default: true
  gimmetag.tag.suicide:
    default: true
